
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNav from "./ui/dashboard/sidenav";
import { useState } from "react";
import Navbar from "./ui/navbar";
import { ThemeProvider } from '@mui/material/styles';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import theme from '../theme';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
   <AppRouterCacheProvider>
         <ThemeProvider theme={theme}>
              {children}       </ThemeProvider>
          </AppRouterCacheProvider>
        {/* <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none  md:w-40">
           <SideNav /> 
          </div>
          <div className="flex-grow p-2 md:overflow-y-auto md:p-4">
            {children}
          </div>
        </div> */}
      </body>
    </html>
  );
}
